### ISSUE TITLE
metrics不能改？我要改metric为auc，！？

### ISSUE THREAD

**Issue by fkuabc** [nuster1128/RecBole-MetaRec#7]
metrics不能改？我要改metric为auc，为什么不能改！？
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    metaQuickStart(modelName, datasetName)
  File "/home/RecBole-MetaRec/recbole_metarec/MetaUtils.py", line 359, in metaQuickStart
    best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)
  File "/home/RecBole/recbole/trainer/trainer.py", line 352, in fit
    valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
  File "/home/RecBole/recbole/trainer/trainer.py", line 210, in _valid_epoch
    valid_score = calculate_valid_score(valid_result, self.valid_metric)
  File "/home/RecBole/recbole/utils/utils.py", line 155, in calculate_valid_score
    return valid_result[valid_metric]
KeyError: 'mrr@5'

**Comment by fkuabc** [comment]
What piece of shxt are you guys writing? Errors when running with the default configuration, the main branch runs fuxxing errors, and other branches also run errors, much less to change the metrics, . waste of my time you fuxxing piece of shxt
 Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    metaQuickStart(modelName, datasetName)
  File "/home/RecBole-MetaRec/recbole_metarec/MetaUtils.py", line 347, in metaQuickStart
    train_data, valid_data, test_data = meta_data_preparation(config, dataset)
  File "/home/RecBole-MetaRec/recbole_metarec/MetaUtils.py", line 84, in meta_data_preparation
    train_data = MetaDataLoader(config, train_dataset, train_sampler, shuffle=True)
  File "/home/RecBole-MetaRec/recbole_metarec/MetaDataLoader.py", line 49, in __init__
    self.user_list = self.getTaskIdList()
  File "/home/RecBole-MetaRec/recbole_metarec/MetaDataLoader.py", line 119, in getTaskIdList
    return np.unique(self.dataset.inter_feat[self.uid_field].numpy())
AttributeError: 'MetaDataLoader' object has no attribute 'dataset'


epoch 0 training [time: 8.29s, train loss: 3.3184]
INFO  epoch 0 evaluating [time: 0.70s, valid_score: -96.638300]

INFO  epoch 0 training [time: 27.83s, train loss: 0.0000]
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    metaQuickStart(modelName, datasetName)
  File "/home/RecBole-MetaRec/recbole_metarec/MetaUtils.py", line 359, in metaQuickStart
    best_valid_score, best_valid_result = trainer.fit(train_data, valid_data)
  File "/home/RecBole/recbole/trainer/trainer.py", line 352, in fit
    valid_score, valid_result = self._valid_epoch(valid_data, show_progress=show_progress)
  File "/home/RecBole/recbole/trainer/trainer.py", line 209, in _valid_epoch
    valid_result = self.evaluate(valid_data, load_best_model=False, show_progress=show_progress)
  File "/home/RecBole-MetaRec/recbole_metarec/MetaTrainer.py", line 75, in evaluate
    result = self.evaluator.evaluate(struct)
  File "/home/RecBole/recbole/evaluator/evaluator.py", line 40, in evaluate
    metric_val = self.metric_class[metric].calculate_metric(dataobject)
  File "/home/RecBole/recbole/evaluator/metrics.py", line 406, in calculate_metric
    return self.output_metric('rmse', dataobject)
  File "/home/RecBole/recbole/evaluator/base_metric.py", line 118, in output_metric
    result = self.metric_info(preds, trues)
  File "/home/RecBole/recbole/evaluator/metrics.py", line 409, in metric_info
    return np.sqrt(mean_squared_error(trues, preds))
  File "/home/data/conda_envs/pytorch/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/home/data/conda_envs/pytorch/lib/python3.8/site-packages/sklearn/metrics/_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/home/data/conda_envs/pytorch/lib/python3.8/site-packages/sklearn/utils/validation.py", line 899, in check_array
    _assert_all_finite(
  File "/home/data/conda_envs/pytorch/lib/python3.8/site-packages/sklearn/utils/validation.py", line 146, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
